# Build stage
FROM gradle:8.11.1-jdk21 AS build
WORKDIR /app
COPY . .
RUN gradle :api-gateway:build -x test --no-daemon

# Run stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/api-gateway/build/libs/*.jar app.jar
EXPOSE 8080
CMD ["java", "-jar", "app.jar"]

